sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "cE90n4ThzATYolLyu6in9/XrOK7Rz6dklbVmd1G6HxSSWpmhVcRukdaDskJwSuKwM+6iPvlr9A1bg5TafqxmSiJvWkLR+qEl2Vne/6gkzaIBwePVdfDX5Dq8H/+IzlFMcU1mvYIe6CQdkJ3mVWb816Cpfw+leyW5LQenF5LrGsLDluZB62qaf3zJz6yN/CvdwyJ968Mim9aQzEHN4iGAtGzWouW7mddOXfHKsb46AZlgvSVpAr/hcFLzOI892e9zdad+nuQ7XR78dE0gTSi8KfvCSVKeGRBUbQ0VHtr6Vc01NEeFrhhCUMZN9CeuM+9wP+n3hpO8ndHz0X/Y48jWGmscaKV2smbzUX4TaV/FLsZAszgFW+BjZvlvodFVcsVVsuCZ5A9UZOgCL3HViI8+mnxk6VpabZoG+fNibzwCDwJQLZ4wBTRJdroAaJlhPMJI/zPltW8SNar5r4EwoybAZlDiMUeu7A4xgpy1PV91NIKpGsdLl52MWiKxK/3iGFtReiN2zLg3rwZWJzXWD0+6winpIo3qNFjUWEKMAh/HE+mIyBt2WFlB7YUyzGOdguQbk6Wc4ulY53rGvClhyxR4WHc6oioZLmyCx4C5tdGo+8Z3d+zQjLn/rZBEFCiM8DXWu2SvFuJZurWkPDm3K35Q4AGwbJ7GnsyocXKtKEa1zLs="
branches:
  only:
    - master
